GET http://localhost:3001/api/phonebook

###
POST http://localhost:3001/api/phonebook HTTP/1.1
Content-Type: application/json

{
    "name": "Trina",
    "number": "519-736-5455"
}


###
PUT http://localhost:3001/api/phonebook/5fe793787ca6734a2f86b076 HTTP/1.1
Content-Type: application/json

{
    "name": "Trina",
    "number": "adsfsdfsf"
}

//"number": "123-123-1234"
###
GET http://localhost:3001/api/phonebook/5fasdf

###
DELETE http://localhost:3001/api/phonebook/780

###
GET https://fast-mountain-98219.herokuapp.com/api/phonebook

###
POST https://fast-mountain-98219.herokuapp.com/api/phonebook/ HTTP/1.1
Content-Type: application/json

{
    "name": "Tyler",
    "number": "5197365455" 
}
